### ISSUE TITLE
Feeds marked as broken

### ISSUE THREAD

**Issue by onli** [superfeedr/documentation#102]
[In my feedreader](https://github.com/onli/feedtragon/blob/d5273d134c9e970d62c095c3e79aa24e369ca24d/server.rb#L127), I have the following code to detect when a feed is broken:

```
if notification["status"]["code"] != 0 && (Time.now - Time.at(notification["status"]["lastParse"])) > 604800
# this was not a ping && for more than a week superfeedr was unable to parse this, so we need to unsubscribe to reduce load
```

The comment explains the intention. This worked fine I think for a while, but recently I noticed that many feeds are not getting notifications anymore. Now my server has a problem and I went into the superfeedr console to unsubscribe all feeds (since the endpoint is down and might change), and notice that half of all the feeds I was subscribed to are now unsubscribed. This includes non-broken feeds like http://rss.escapistmagazine.com/videos/list/1.xml and https://www.deimeke.net/dirk/blog/index.php?/feeds/index.rss2. My questions:
1. Did something change on your end explaining the vanished feeds
2. What are the correct markers to detect that a feed is broken and should be unsubscribed?

**Comment by onli** [comment]
No reaction to this? If superfeedr can't read valid feeds anymore, or is unable to realiably fetch them, this could be a critical issue. And if not, clearing up how to properly handle broken feeds in general (is the code above how to do this?) would still be very useful, and something that fell short in earlier issues here. @julien51, you are on another project now and there was no replacement for you?

**Comment by julien51** [comment]
I am so sorry for the delay. I missed your messages... and only got this one because github sent me a message after your mention :/

To answer your specific questions:
1. We did not change anything on how we detect broken feeds. I am not sure why the feeds "vanished". Could it be that you unsubscribed from these feeds on your end?
2. I believe your code is right... but I think this is probably too strict. One week is too short. Let's say a feed has 20 entries and publishes 1 story per day. If a single entry is actually causing the issue with broken markup, the feed will be broken for 20 days. Also you should check that the lastParse parse value exists. For example, for new feeds before we have actually been able to parse them, we do actually return a lastParse being our "epoch" and it is indeed beyond 7 days. You should maybe check a little more things on your end, like how "old" the feed is in your own database.

**Comment by onli** [comment]
Thanks for your answer. The delay itself is no problem, just feeds the usual fear when a startup gets bought and had excellent support before ;)

 1. Yes, absolutely. It is possible my side unsubscribed, but that would only happen via the code I showed.
 2. Okay. I will make this less strict, trying to rely a bit more on internal logic on my side as well, and have a closer look at problematic feeds like the feed of xkcd. 

But: If a feed really is broken for 20 days, would superfeedr not send many notifications about that, counting each time? I'm currently trying to get those things in order because I'll try to run a installation of my feedreader with multiple users, fully expecting to finally go over your 10k free limit. But multiple users with multiple broken feeds for a longer time (counting on one superfeedr account of course) sounds costly, doesn't it? Or am I overestimating how many notifications superfeedr would send – is it more one per day or one each 15 minutes?

**Comment by julien51** [comment]
If a feed is broken for 20 days, you will get notifications about it as we send notifications every time we found it broken (HTTP or parsing issues).
We do back-off though on broken feeds, which means that you will quickly receive only 1 notification per day per broken feed. I understand and agree this is sub-optimal but I think it's also not too bad.

We are working on improving our pricing scheme, so stay tuned!
