### ISSUE TITLE
JSON Feed support

### ISSUE THREAD

**Issue by JS1010111** [superfeedr/documentation#123]
Is it possible to subscribe to JSON Feeds like `http://inessential.com/feed.json` or `https://daringfireball.net/feeds/json` and receive messages from Superfeedr with the same schema as XML based feeds subscriptions (https://documentation.superfeedr.com/schema.html)?

**Comment by hwo411** [comment]
Would be great to have them supported! The current behavior doesn't match the behavior with RSS/Atom.

**Comment by julien51** [comment]
They are supported!

**Comment by hwo411** [comment]
@julien51 thanks for replying. When I tested them last time, they worked too differently from RSS and Atom. I tried to use them around 1 month ago (if anything changed recently, then let me know, I'll recheck).

The first difference was that when I use
POST https://push.superfeedr.com with retrieve=true, I do not receive all the items from the feed. That already means we need a special handling for them, while all other tools that can process them afterwards work the same way for both JSON Feeds and RSS/Atom.

So while they're supported, they're definitely different from RSS/Atom, which is quite similar as not supporting them at all.

Your document also says that you send the whole document on updates. That's also different from how RSS and Atom work. The code to handle this might be slightly easier to update, but still it's not the same behavior.

I haven't checked GET https://push.superfeedr.com, because I already stopped on POST, but if it also behaves differently, that make no sense to treat JSON feeds as "supported" for our use cases.
