### ISSUE TITLE
Support for podcasts

### ISSUE THREAD

**Issue by svenwiegand** [superfeedr/documentation#18]
Your service sound quite promising and I would be interested in using for podcasts. Unfortunately due to the documentation it looks as if information required for podcasts (e.g. the RSS enclosure element and the itunes namespace) isn't supported. Is that right?

**Comment by AnalogJ** [comment]
Hey @julien51 is there any eta on when you would be adding support for podcasts to superfeedr? 
I'm trying to get the enclosure field from items in http://feeds.gimletmedia.com/mysteryshow but it doesn't show up in my webhook json data. 

The weird thing is that it does work for some of the other rss feeds that I'm subscribed to.

**Comment by julien51** [comment]
Jason,

All `<enclosure>` items are turned into `<link>` elements  with a
`rel=enclosure` attribute in our schema, because this is what they are :)

Julien

On Sat, Jul 18, 2015 at 6:57 PM, Jason Kulatunga <notifications@github.com>
wrote:

> Hey @julien51 <https://github.com/julien51> is there any eta on when you
> would be adding support for podcasts to superfeedr?
> I'm trying to get the enclosure field from items in
> http://feeds.gimletmedia.com/mysteryshow but it doesn't show up in my
> webhook json data.
>
> The weird thing is that it does work for some of the other rss feeds that
> I'm subscribed to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/superfeedr/documentation/issues/18#issuecomment-122563817>
> .
>



-- 
Julien Genestoux
Superfeedr <https://superfeedr.com/>
julien@superfeedr.com
4158306574

**Comment by AnalogJ** [comment]
Hey Julien, 
Thats exactly what I expected to happen, however I've created a gist with an example server payload, as well as a rss feed request.  All I've done to the raw rss feed is formatted it and removed the unnecessary items. 

https://gist.github.com/AnalogJ/ef51249f43822c6af036

As you can see the rss feed has:

    <enclosure url="http://feeds.wnyc.org/~r/mysteryshow-gimlet/~5/nqlMUmTni-w/mysteryshow061915_sourcecode_pod.mp3" length="0" type="audio/mpeg" />

However the payload recieved by my server only has the following `standardLinks` and there's no `enclosure` key in the dictionary as I've seen in other podcasts. 

     "standardLinks": {
       "alternate": [
         {
           "title": "Case #5 Source Code",
           "rel": "alternate",
           "href": "http://feeds.wnyc.org/~r/mysteryshow-gimlet/~3/DpHWYtpocWU/",
           "type": "text/html"
         }
       ],
       "canonical": [
           "rel": "canonical",
           "href": "http://www.wnyc.org/story/case-5-source-code/",
       ]
     },

Even the `source` key which I assumed would be the raw parsed values from the rss feed seems to be missing that key.

**Comment by julien51** [comment]
Thanks @AnalogJ 
Indeed, I just run a couple tests and you are right, something is odd. What's even stranger is that in our test suite, we do however have the right links... encluding an `enclosure` element in `standardLinks`.

Working on it!

**Comment by julien51** [comment]
Ok, this is extremely puzzling. Do you know if by any chance the format of the feed changed in the last couple days? My belief is that the `<enclosure>` element was recently added to the RSS feed... 

Here's what I did: I subscribed to `http://feeds.gimletmedia.com/mysteryshow?debug=j` (note the `?debug=j` extra query string). It's a different URL so a brand new feed for Superfeedr, but of course the content is the same because this query string does not make any sense to the gimletmedia.com servers.

I subscribed using this callback url: `http://requestb.in/vlxo12vl` for which you can easily [inspect the traffic here](http://requestb.in/vlxo12vl?inspect). You'll see that the notifications received for this feed do have the `enclosure` element in the `standardLinks` for `items`...

So, from there, what I can do is simple: I can clear our local cache for [http://feeds.gimletmedia.com/mysteryshow](http://feeds.gimletmedia.com/mysteryshow) so you'll receive the content again, but with the `enclosure` elements too.

Does it make sense?
